#! /bin/bash

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

bspc monitor -d α β γ δ ε ζ η θ

#bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2

# launch stuff
panel &

